version: '2'
services:
  site:
    image: "tehusername/ronin-pug"
    ports:
      - 5015:3000
    restart: always
    volumes:
      - data-scraped:/src/scraped
  scraper:
    image: tehusername/pyselfox
    volumes:
      - ./modules/scraper:/src
      - data-scraped:/src/scraped
volumes:
  data-scraped:
